name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Deploy application
      if: ${{github.ref == 'refs/heads/main' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nutrifollow" #Must be unique in Heroku
          heroku_email: "yresendeo@gmail.com"
          buildpack: "https://github.com/zidizei/heroku-buildpack-tsc#v2.0"